### ISSUE TITLE
[DATE]: Authentication Feature for OSCSA MOOCs platform

### ISSUE THREAD

**Issue by anslemkelechi** [Open-Science-Community-Saudi-Arabia/MOOCs#6]
### Description 

I would be working on the authentication feature of the API,  this feature should contain the following functionalities according to the tasks listed below

### Tasks needed to be carried out?

- [ ] *Creating a user model based on the application needs*
- [ ] *Adding a signup route to the API*
- [ ] *Adding a login route to the API*
- [ ] *Implementing Statelessness Using JWT for sessions*
- [ ] *Adding a logout route*
- [ ] *Building a password reset route*
- [ ] *Adding social signin/signup*

### Technology Used 

*Nodejs*
*Express.js*
*MongoDB*
*JWT*

### Feedback

I would be working on this issue and following updates on parent issue #5
