### ISSUE TITLE
[13-10-2022]: Authentication feature for OSCSA MOOCs platform

### ISSUE THREAD

**Issue by anslemkelechi** [Open-Science-Community-Saudi-Arabia/MOOCs#7]
#### Description

I would be working on the authentication feature of the API,  this feature should contain the following functionalities according to the tasks listed below

#### Tasks

- [ ] *Creating a user model based on the application needs*
- [ ] *Adding a signup route to the API*
- [ ] *Adding a login route to the API*
- [ ] *Implementing Statelessness Using JWT for sessions*
- [ ] *Adding a logout route*
- [ ] *Building a password reset route*
- [ ] *Adding social signin/signup*

### Technology Used 

*Nodejs*
*Express.js*
*MongoDB*
*JWT*

### Feedback

I would be working on this issue and following updates on parent issue #5

**Comment by RealRichi3** [comment]
@anslemkelechi i already merged the models here #30, you can check it out if you got something to add

**Comment by BatoolMM** [comment]
If this issue has been addressed, can we close this issue?
