### ISSUE TITLE
[13-10-2022]: Course/Video feature for OSCSA Website

### ISSUE THREAD

**Issue by ORIYOMI289** [Open-Science-Community-Saudi-Arabia/MOOCs#8]
#### Description

model and CRUD operation on the videos/courses

#### Task?

- [ ] *Database model for courses/videos*
- [ ] *Create/Upload Course (restricted to admin).*
- [ ] *Update course details (restricted to admin).*
- [ ] *Delete course (restricted to admin)*
- [ ] *Get all data for particular course (should include exercises if any)*
- [ ] *Get all available courses*

### Technology?

- [ ] *NodeJs.*
- [ ] *mongoDB.*
- [ ]  *ExpressJs*
- [ ]  *cloudinary*

### Feedback?

I will be working on this issue

**Comment by BatoolMM** [comment]
Thank you @ORIYOMI289 for creating a very clear issue, let me know if you need anything from my side!

**Comment by ORIYOMI289** [comment]
@BatoolMM alright

**Comment by ORIYOMI289** [comment]
pls i need the figma design for this project

**Comment by ORIYOMI289** [comment]
@BatoolMM pls assign this issue to me
